-- MySQL Script generated by MySQL Workbench
-- Wed Oct 24 10:46:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema record
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `record` ;

-- -----------------------------------------------------
-- Schema record
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `record` DEFAULT CHARACTER SET utf8 ;
USE `record` ;

-- -----------------------------------------------------
-- Table `record`.`server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`server` ;

CREATE TABLE IF NOT EXISTS `record`.`server` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `host_name` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`ioc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`ioc` ;

CREATE TABLE IF NOT EXISTS `record`.`ioc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `install_path` VARCHAR(45) NULL,
  `boot_time` DATETIME NULL,
  `active` TINYINT(1) NULL,
  `servier_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_server_id_idx` (`servier_id` ASC),
  CONSTRAINT `fk_server_id`
    FOREIGN KEY (`servier_id`)
    REFERENCES `record`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`record_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`record_type` ;

CREATE TABLE IF NOT EXISTS `record`.`record_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`record` ;

CREATE TABLE IF NOT EXISTS `record`.`record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `record_type_id` INT NULL,
  `active` TINYINT(1) NULL,
  `ioc_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ioc_id_idx` (`ioc_id` ASC),
  INDEX `fk_record_type_id_idx` (`record_type_id` ASC),
  CONSTRAINT `fk_ioc_id`
    FOREIGN KEY (`ioc_id`)
    REFERENCES `record`.`ioc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_type_id`
    FOREIGN KEY (`record_type_id`)
    REFERENCES `record`.`record_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`field_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`field_name` ;

CREATE TABLE IF NOT EXISTS `record`.`field_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`record_field_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`record_field_type` ;

CREATE TABLE IF NOT EXISTS `record`.`record_field_type` (
  `record_type_id` INT NOT NULL,
  `field_name_id` INT NOT NULL,
  INDEX `fk_record_type_id_idx` (`record_type_id` ASC),
  INDEX `fk_field_type_id_idx` (`field_name_id` ASC),
  PRIMARY KEY (`record_type_id`, `field_name_id`),
  CONSTRAINT `fk1_record_type_id`
    FOREIGN KEY (`record_type_id`)
    REFERENCES `record`.`record_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk1_field_name_id`
    FOREIGN KEY (`field_name_id`)
    REFERENCES `record`.`field_name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`field_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`field_value` ;

CREATE TABLE IF NOT EXISTS `record`.`field_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `field_name_id` INT NULL,
  `record_id` INT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_record_id_idx` (`record_id` ASC),
  INDEX `fk_field_name_id_idx` (`field_name_id` ASC),
  CONSTRAINT `fk_field_name_id`
    FOREIGN KEY (`field_name_id`)
    REFERENCES `record`.`field_name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_id`
    FOREIGN KEY (`record_id`)
    REFERENCES `record`.`record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
