-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 14:41:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema record
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `record` ;

-- -----------------------------------------------------
-- Schema record
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `record` DEFAULT CHARACTER SET utf8 ;
USE `record` ;

-- -----------------------------------------------------
-- Table `record`.`server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`server` ;

CREATE TABLE IF NOT EXISTS `record`.`server` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(45) NULL,
  `startup_time` DATETIME NULL,
  `scan_time` DATETIME NULL,
  `os_vers` VARCHAR(45) NULL,
  `mem_total` VARCHAR(45) NULL,
  `mem_free` VARCHAR(45) NULL,
  `buffers` VARCHAR(45) NULL,
  `cached` VARCHAR(45) NULL,
  `cpu_load` VARCHAR(45) NULL,
  `load_average` VARCHAR(45) NULL,
  `cpu_model` VARCHAR(45) NULL,
  `cpu_num` VARCHAR(45) NULL,
  `file_free` INT NULL,
  `file_max` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`ioc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`ioc` ;

CREATE TABLE IF NOT EXISTS `record`.`ioc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `install_path` VARCHAR(45) NULL,
  `boot_time` DATETIME NULL,
  `scan_time` DATETIME NULL,
  `active` TINYINT(1) NULL,
  `servier_id` INT NULL,
  `epics_ca_server_port` VARCHAR(45) NULL,
  `epics_ca_repeater_port` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_server_id_idx` (`servier_id` ASC),
  CONSTRAINT `fk_server_id`
    FOREIGN KEY (`servier_id`)
    REFERENCES `record`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`record_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`record_type` ;

CREATE TABLE IF NOT EXISTS `record`.`record_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`record` ;

CREATE TABLE IF NOT EXISTS `record`.`record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `record_type_id` INT NULL,
  `active` TINYINT(1) NULL,
  `ioc_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ioc_id_idx` (`ioc_id` ASC),
  INDEX `fk_record_type_id_idx` (`record_type_id` ASC),
  CONSTRAINT `fk_ioc_id`
    FOREIGN KEY (`ioc_id`)
    REFERENCES `record`.`ioc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_type_id`
    FOREIGN KEY (`record_type_id`)
    REFERENCES `record`.`record_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`field_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`field_group` ;

CREATE TABLE IF NOT EXISTS `record`.`field_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`field_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`field_type` ;

CREATE TABLE IF NOT EXISTS `record`.`field_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desp` VARCHAR(100) NULL,
  `field_group_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_group_id_idx` (`field_group_id` ASC),
  CONSTRAINT `fk_field_group_id`
    FOREIGN KEY (`field_group_id`)
    REFERENCES `record`.`field_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`field_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`field_value` ;

CREATE TABLE IF NOT EXISTS `record`.`field_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `field_type_id` INT NULL,
  `record_id` INT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_record_id_idx` (`record_id` ASC),
  INDEX `fk_field_name_id_idx` (`field_type_id` ASC),
  CONSTRAINT `fk_field_type_id`
    FOREIGN KEY (`field_type_id`)
    REFERENCES `record`.`field_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_id`
    FOREIGN KEY (`record_id`)
    REFERENCES `record`.`record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`server_env`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`server_env` ;

CREATE TABLE IF NOT EXISTS `record`.`server_env` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `env_name` VARCHAR(45) NULL,
  `env_value` VARCHAR(45) NULL,
  `server_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_server_id_idx` (`server_id` ASC),
  CONSTRAINT `fk_fk_server_id`
    FOREIGN KEY (`server_id`)
    REFERENCES `record`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`epics_env`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`epics_env` ;

CREATE TABLE IF NOT EXISTS `record`.`epics_env` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `epics_env_name` VARCHAR(45) NULL,
  `epics_env_value` VARCHAR(45) NULL,
  `server_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `ffk_server_id_idx` (`server_id` ASC),
  CONSTRAINT `ffk_server_id`
    FOREIGN KEY (`server_id`)
    REFERENCES `record`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `record`.`record_type_field_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `record`.`record_type_field_type` ;

CREATE TABLE IF NOT EXISTS `record`.`record_type_field_type` (
  `record_type_id` INT NOT NULL,
  `field_type_id` INT NOT NULL,
  PRIMARY KEY (`record_type_id`, `field_type_id`),
  INDEX `fk1_field_type_idx` (`field_type_id` ASC),
  INDEX `fk1_record_type_idx` (`record_type_id` ASC),
  CONSTRAINT `fk1_record_type_idx`
    FOREIGN KEY (`record_type_id`)
    REFERENCES `record`.`record_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk1_field_type_idx`
    FOREIGN KEY (`field_type_id`)
    REFERENCES `record`.`field_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
